server:
  port: 8091

spring:
  application:
    name: msvc-colors

  profiles:
    active: dev

eureka:
  instance:
    hostname: localhost

  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
