server:
  port: 8092

  servlet:
    context-path: /api/v0/crop

spring:
  profiles:
    active: prod

eureka:
  instance:
    hostname: localhost

  client:
    serviceUrl: http://localhost:8761/eureka
