server:
  port: 8094

  servlet:
    context-path: /api/${spring.api.version}/invert-colors

spring:
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

eureka:
  instance:
    hostname: localhost
    preferIpAddress: true

  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: always

logging:
  level:
    "[xyz.cupscoffee]": debug

  pattern:
    dateformat: HH:mm:ss
    level: "%highlight(%-5level)"
    console: "%clr(%d{HH:mm:ss}){faint} %highlight(%-5level) ---
      [%clr(${spring.application.name:-}){yellow}] %clr(%-45.45logger{45}){cyan}
      %clr(:){faint} %m%n"

springdoc:
  api-docs:
    server-url: http://${server.host}${server.servlet.context-path}

  swagger-ui:
    path: /docs
    operationSorter: method
    tagsSorter: alpha
