server:
  port: 8080

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

      routes:
        - id: colors
          uri: lb://msvc-colors
          predicates:
            - Path=/api/v0/colors/**
          filters:
            - StripPrefix=0

        - id: crop
          uri: lb://msvc-crop
          predicates:
            - Path=/api/v0/crop/**
          filters:
            - StripPrefix=0

        - id: resize
          uri: lb://msvc-resize
          predicates:
            - Path=/api/v0/resize/**
          filters:
            - StripPrefix=0

        - id: invert-colors
          uri: lb://msvc-invert-colors
          predicates:
            - Path=/api/v0/invert-colors/**
          filters:
            - StripPrefix=0

        - id: ui
          uri: lb://msvc-ui
          predicates:
            - Path=/**
          filters:
            - StripPrefix=0

      globalcors:
        corsConfigurations:
          "[/**]":
            allowedOrigins:
              - "https://image-coffee-utils.cupscoffee.xyz"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
            allowedHeaders:
              - "*"
            allowCredentials: true

eureka:
  client:
    register-with-eureka: false

logging:
  pattern:
    dateformat: HH:mm:ss
    level: "%highlight(%-5level)"
    console: "%clr(%d{HH:mm:ss}){faint} %highlight(%-5level) ---
      [%clr(${spring.application.name:-}){yellow}] %clr(%-45.45logger{45}){cyan}
      %clr(:){faint} %m%n"
