server:
  port: 8090

spring:
  application:
    name: msvc-ui

  mvc:
    view:
      suffix: .xhtml

eureka:
  instance:
    hostname: localhost

  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: always

logging:
  level:
    "[org.springframework.cloud]": debug

  pattern:
    dateformat: HH:mm:ss
    level: "%highlight(%-5level)"
    console: "%clr(%d{HH:mm:ss}){faint} %highlight(%-5level) ---
      [%clr(${spring.application.name:-}){yellow}] %clr(%-45.45logger{45}){cyan}
      %clr(:){faint} %m%n"
