server:
  port: 8761

spring:
  application:
    name: msvc-eureka

eureka:
  instance:
    hostname: localhost

  client:
    register-with-eureka: false
    fetch-registry: false

    serverUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

logging:
  pattern:
    dateformat: HH:mm:ss
    level: "%highlight(%-5level)"
    console: "%clr(%d{HH:mm:ss}){faint} %highlight(%-5level) ---
      [%clr(${spring.application.name:-}){yellow}] %clr(%-45.45logger{45}){cyan}
      %clr(:){faint} %m%n"
