server:
  port: 8094

  servlet:
    context-path: /api/${spring.api.version}/invert-colors

spring:
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

  devtools:
    livereload:
      enabled: false

    restart:
      enabled: false
      additional-exclude: "**"

eureka:
  instance:
    hostname: ${SPRING_CLOUD_EUREKA_HOSTNAME:localhost}
    preferIpAddress: true

  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka

logging:
  pattern:
    level: "%highlight(%-5level)"
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %highlight(%-5level)
      %clr(${PID:- }){magenta} %clr(---){faint}
      [%clr(${spring.application.name:-}){yellow}] %clr(%-45.45logger{45}){cyan}
      %clr(:){faint} %m%n"

  file:
    path: logs
    name: logs/msvc-invert-colors.log

  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 7

springdoc:
  api-docs:
    server-url: https://${server.host}${server.servlet.context-path}

  swagger-ui:
    path: /docs
    operationSorter: method
    tagsSorter: alpha
