server:
  port: 8092

  servlet:
    context-path: /api/v0/crop

spring:
  profiles:
    active: dev

eureka:
  instance:
    hostname: ${SPRING_CLOUD_EUREKA_HOSTNAME:localhost}
    preferIpAddress: true

  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka
