server:
  port: 8761

eureka:
  instance:
    hostname: ${SPRING_CLOUD_EUREKA_HOSTNAME:localhost}
    preferIpAddress: true

  client:
    register-with-eureka: false
    fetch-registry: false

    serverUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

logging:
  pattern:
    level: "%highlight(%-5level)"
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %highlight(%-5level)
      %clr(${PID:- }){magenta} %clr(---){faint}
      [%clr(${spring.application.name:-}){yellow}] %clr(%-45.45logger{45}){cyan}
      %clr(:){faint} %m%n"
