server:
  port: 8091

spring:
  application:
    name: msvc-colors

  profiles:
    active: prod

eureka:
  instance:
    hostname: ${SPRING_CLOUD_EUREKA_HOSTNAME:localhost}
    preferIpAddress: true

  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka
