spring:
  application:
    name: msvc-config

  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config/dev

  output:
    ansi:
      enabled: always

logging:
  pattern:
    dateformat: HH:mm:ss
    level: "%highlight(%-5level)"
    console:
      "%clr(%d{HH:mm:ss}){faint} %highlight(%-5level) ---
      [%clr(${spring.application.name:-}){yellow}] %clr(%-45.45logger{45}){cyan}
      %clr(:){faint} %m%n"
